# Notebook Instructions

1. If you are new to Jupyter notebooks, please go through this introductory manual <a href='https://quantra.quantinsti.com/quantra-notebook' target="_blank">here</a>.
1. Any changes made in this notebook would be lost after you close the browser window. **You can download the notebook to save your work on your PC.**
1. Before running this notebook on your local PC:<br>
i.  You need to set up a Python environment and the relevant packages on your local PC. To do so, go through the section on "**Run Codes Locally on Your Machine**" in the course.<br>
ii. You need to **download the zip file available in the last unit** of this course. The zip file contains the data files and/or python modules that might be required to run this notebook.

## Import Time Series Data

There are a number of ways available to fetch financial time series data. You either use Python packages to download the data or you can read the data stored in a CSV file.

In this notebook, you will learn the following ways:

1. [Import Data from Yahoo Finance](#y-finance)<br>
2. [Read Data from a CSV File](#read-data)


<a id='y-finance'></a> 
## Import Data from Yahoo Finance

To fetch data from Yahoo finance, you need to first install the `yfinance` package. You can do it using the `pip` command. The `pip` command is a tool for installing and managing Python packages.

```python
!pip install yfinance
```

You can fetch data from `yfinance` package using the `download` method.

Syntax:
```python
import yfinance as yf
yf.download(ticker, start, end)
```
1. **ticker:** Ticker of the stock
2. **start:** Start date
3. **end:** End date

In [2]:
%pip install yfinance

Collecting yfinance
  Downloading yfinance-0.2.40-py2.py3-none-any.whl (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 KB 862.9 kB/s eta 0:00:001m764.0 kB/s eta 0:00:01
Collecting peewee>=3.16.2
  Downloading peewee-3.17.5.tar.gz (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 8.1 MB/s eta 0:00:00[31m7.9 MB/s eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting html5lib>=1.1
  Using cached html5lib-1.1-py2.py3-none-any.whl (112 kB)
Requirement already satisfied: beautifulsoup4>=4.11.1 in ./env/lib/python3.10/site-packages (from yfinance) (4.12.3)
Collecting frozendict>=2.3.4
  Downloading frozendict-2.4.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.3/117.3 KB 9.2 MB/s eta 0:00:00
Requirement already satisfied: requests>=2.31 in ./env/lib/python3.10/site-packages (from yfinance) (2.32.2)
Collecting pytz>=2022.5
  Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Collecting pandas>=1.3.0
  Using cached pandas-2.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.0 MB)
Collecting multitasking>=0.0.7
  Using cached multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Requirement already satisfied: platformdirs>=2.0.0 in ./env/lib/python3.10/site-packages (from yfinance) (4.2.2)
Collecting lxml>=4.9.1
  Downloading lxml-5.2.2-cp310-cp310-manylinux_2_28_x86_64.whl (5.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 10.1 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Collecting numpy>=1.16.5
  Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Requirement already satisfied: soupsieve>1.2 in ./env/lib/python3.10/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: webencodings in ./env/lib/python3.10/site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: six>=1.9 in ./env/lib/python3.10/site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Collecting tzdata>=2022.7
  Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./env/lib/python3.10/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: idna<4,>=2.5 in ./env/lib/python3.10/site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./env/lib/python3.10/site-packages (from requests>=2.31->yfinance) (2.2.1)
Requirement already satisfied: charset-normalizer<4,>=2 in ./env/lib/python3.10/site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: certifi>=2017.4.17 in ./env/lib/python3.10/site-packages (from requests>=2.31->yfinance) (2024.2.2)
Building wheels for collected packages: peewee
  Building wheel for peewee (pyproject.toml) ... done
  Created wheel for peewee: filename=peewee-3.17.5-py3-none-any.whl size=138635 sha256=76e9d7943ca1dab405696379e90b2d207f9316c07a627b38788789ce81ffc39c
  Stored in directory: /home/bernardo/.cache/pip/wheels/06/80/9b/98db0d58349a2f5c09f8406789ade4270762f97b7d26f2fa22
Successfully built peewee
Installing collected packages: pytz, peewee, multitasking, tzdata, numpy, lxml, html5lib, frozendict, pandas, yfinance
Successfully installed frozendict-2.4.4 html5lib-1.1 lxml-5.2.2 multitasking-0.0.11 numpy-1.26.4 pandas-2.2.2 peewee-3.17.5 pytz-2024.1 tzdata-2024.1 yfinance-0.2.40
Note: you may need to restart the kernel to use updated packages.

In [3]:
# Import yfinance
import yfinance as yf

# Fetch the Coca Cola price data
data = yf.download('KO', start="2019-01-01", end="2021-03-31")

# Display the data
data.head()

[*********************100%%**********************]  1 of 1 completed

                 Open       High        Low      Close  Adj Close    Volume
Date
2019-01-02  46.939999  47.220001  46.560001  46.930000  39.828796  11603700
2019-01-03  46.820000  47.369999  46.529999  46.639999  39.582684  14714400
2019-01-04  46.750000  47.570000  46.639999  47.570000  40.371948  13013700
2019-01-07  47.570000  47.750000  46.900002  46.950001  39.845776  13135500
2019-01-08  47.250000  47.570000  47.040001  47.480000  40.295574  15420700

From the above output, you can see that the data imported has the close as well as the adjusted close price. The other information available are the open price, high price, low price and volume.

You can also fetch the adjusted price data from `yfinance` package by adding one more parameter `auto_adjust` in `download`.

Syntax:
```python
yf.download(ticker, start, end, auto_adjust=True)
```
**auto_adjust:** Set this to `True` to download the adjusted price. By default, it is `False`.

In [4]:
# Fetch the adjusted price data
data = yf.download('KO', start="2019-01-01", end="2021-03-31", auto_adjust=True)

# Display the data
data.head()

[*********************100%%**********************]  1 of 1 completed

                 Open       High        Low      Close    Volume
Date
2019-01-02  39.837282  40.074916  39.514784  39.828796  11603700
2019-01-03  39.735447  40.202223  39.489328  39.582684  14714400
2019-01-04  39.676027  40.371948  39.582671  40.371948  13013700
2019-01-07  40.371960  40.524723  39.803342  39.845776  13135500
2019-01-08  40.100377  40.371956  39.922154  40.295574  15420700

Now you have the adjusted price data.

<a id='read-data'></a> 
## Read Data from a CSV File

A CSV (Comma Separated Value) file stores tabular content in form of plain text. The values are separated by a comma. You can use `pandas.read_csv()` to read the CSV file. The stock price of Coca Cola from January 2019 to March 2021 is stored in a CSV file, `coca_cola_price.csv`. It has the following information:

|Column No.|Column Name|
|---|---|
|1.|Date|
|2.|Open|
|3.|High|
|4.|Low|
|5.|Close|
|6.|Adj Close|
|7.|Volume|

Syntax:
```python
import pandas as pd
pd.read_csv(filename,index_col)
```
1. **filename**: Path + name of the file in the string format
2. **index_col**: The column number to set as index (index begins from 0)

In [ ]:
# Import pandas as alias 'pd'
import pandas as pd

# The data is stored in the directory 'data_modules'
path = '../data_modules/'

# Loading the data using CSV file and set 'Date' as the index
coca_cola = pd.read_csv(path + 'coca_cola_price.csv', index_col=0)

# Display the data
coca_cola.head()

                 Open       High        Low      Close  Adj Close    Volume
Date
2019-01-02  46.939999  47.220001  46.560001  46.930000  43.620419  11603700
2019-01-03  46.820000  47.369999  46.529999  46.639999  43.350868  14714400
2019-01-04  46.750000  47.570000  46.639999  47.570000  44.215286  13013700
2019-01-07  47.570000  47.750000  46.900002  46.950001  43.639008  13135500
2019-01-08  47.250000  47.570000  47.040001  47.480000  44.131630  15420700

This is a time series data with `Date` column as the index. So you can convert the index to datetime format. Working with datetime index is much simpler than working with string index as you can do a lot of operations with a datetime object in Python. You can use `pandas.to_datetime` method to convert the index to datetime.

Syntax:
```python
pandas.to_datetime(DataFrame.index)
```

In [ ]:
# Convert the index to date_time format
coca_cola.index = pd.to_datetime(coca_cola.index)

# Display the data
coca_cola.head()

                 Open       High        Low      Close  Adj Close    Volume
Date
2019-01-02  46.939999  47.220001  46.560001  46.930000  43.620419  11603700
2019-01-03  46.820000  47.369999  46.529999  46.639999  43.350868  14714400
2019-01-04  46.750000  47.570000  46.639999  47.570000  44.215286  13013700
2019-01-07  47.570000  47.750000  46.900002  46.950001  43.639008  13135500
2019-01-08  47.250000  47.570000  47.040001  47.480000  44.131630  15420700

You can also explore various other methods to get financial data. Read the blog on [stock market data and analysis](https://blog.quantinsti.com/stock-market-data-analysis-python/) for the same. <br><br>